import type { Product } from "../lib/catalogue";

// Initial catalogue, loaded into the database by `npm run db:seed`.
export const seedProducts: Product[] = [
  {
    slug: "stoneware-mug",
    number: "014",
    name: "Stoneware mug",
    room: "table",
    material: "Ash glaze",
    tagline: "Wheel-thrown stoneware, ash glaze",
    description:
      "A heavy, round mug that holds heat. Thrown on the wheel and dipped in an ash glaze that pools a little darker at the base.",
    price: 12500,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Stoneware",
      size: "9 × 8.5 cm, 350 ml",
      care: "Dishwasher safe. Avoid sudden temperature changes.",
    },
  },
  {
    slug: "iroko-serving-board",
    number: "022",
    name: "Iroko serving board",
    room: "kitchen",
    material: "Oiled iroko wood",
    tagline: "Solid iroko, finished with food-safe oil",
    description:
      "Cut from a single piece of iroko and finished with food-safe oil. Big enough for bread, fruit or a full plate of suya.",
    price: 28000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: {
      material: "Iroko wood",
      size: "45 × 20 cm",
      care: "Hand wash and dry upright. Oil when it looks dry.",
    },
  },
  {
    slug: "enamel-pot-3-litre",
    number: "031",
    name: "Enamel pot, 3 litre",
    room: "kitchen",
    material: "Enamelled steel",
    tagline: "Enamelled steel with a fitted lid",
    description:
      "A light, bright pot for stews, rice and everything in between. Enamelled steel heats quickly and wipes clean.",
    price: 46000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Enamelled steel",
      size: "3 litres",
      care: "Wash by hand. Avoid metal scourers.",
    },
  },
  {
    slug: "linen-tea-towels-pair",
    number: "008",
    name: "Linen tea towels, pair",
    room: "bath-linen",
    material: "Washed linen",
    tagline: "Washed linen, set of two",
    description:
      "Two tea towels in pre-washed linen. They dry fast, leave no lint and get softer every wash.",
    price: 15000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: {
      material: "100% linen",
      size: "70 × 50 cm each",
      care: "Machine wash warm. Line dry.",
    },
  },
  {
    slug: "brass-wall-hooks-pair",
    number: "040",
    name: "Brass wall hooks, pair",
    room: "tools",
    material: "Solid brass",
    tagline: "Solid brass, screws included",
    description:
      "Two simple hooks in solid brass for keys, bags and towels. Left unlacquered, so they darken gently over time.",
    price: 9500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: {
      material: "Solid brass",
      size: "6 cm tall, 4 cm deep",
      care: "Wipe with a dry cloth. Polish if you prefer it bright.",
    },
  },
  {
    slug: "clay-water-pot",
    number: "017",
    name: "Clay water pot",
    room: "kitchen",
    material: "Unglazed terracotta",
    tagline: "Unglazed terracotta, with a wooden lid",
    description:
      "Unglazed clay keeps water cool the old way: a little seeps through the wall and evaporates, taking the heat with it. Thrown by hand, fired low and finished with a carved lid. Each one comes out slightly different.",
    price: 32000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [
      { name: "Natural", swatch: "#b8714f" },
      { name: "Burnished", swatch: "#8c4a2f" },
      { name: "Smoked", swatch: "#3a2f2a" },
    ],
    details: {
      material: "Terracotta, iroko lid",
      size: "5 litres · 32 × 24 cm",
      care: "Rinse with water only. No soap, no dishwasher.",
    },
  },
  {
    slug: "grid-notebook-a5",
    number: "052",
    name: "Grid notebook, A5",
    room: "paper-desk",
    material: "Recycled paper",
    tagline: "Recycled paper, lay-flat binding",
    description:
      "An A5 notebook with a faint grid, printed on recycled paper and bound to lie flat. For lists, sums and sketches.",
    price: 6500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Recycled paper",
      size: "A5",
      care: "Keep dry.",
    },
  },
  {
    slug: "woven-bread-basket",
    number: "026",
    name: "Woven bread basket",
    room: "table",
    material: "Hand-woven raffia",
    tagline: "Hand-woven raffia",
    description:
      "A shallow basket woven by hand from raffia. Use it for bread, fruit or anything that needs somewhere to sit.",
    price: 18500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: {
      material: "Raffia",
      size: "30 cm across",
      care: "Shake out crumbs. Wipe with a damp cloth.",
    },
  },
  {
    slug: "wooden-spoon-set",
    number: "023",
    name: "Wooden spoon set",
    room: "kitchen",
    material: "Carved hardwood",
    tagline: "Three hand-carved cooking spoons",
    description:
      "A stirring spoon, a flat turner and a small tasting spoon, each carved from a single piece of hardwood. Smooth, sturdy and kind to every pot.",
    price: 9000,
    isNew: true,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Hardwood", size: "30, 28 and 20 cm long", care: "Hand wash and dry. Oil now and then." },
  },
  {
    slug: "wooden-mortar-and-pestle",
    number: "029",
    name: "Wooden mortar and pestle",
    room: "kitchen",
    material: "Turned hardwood",
    tagline: "For pepper, spices and garlic",
    description:
      "A deep, heavy mortar turned from hardwood, with a long pestle for pounding pepper, spices and garlic. Built to sit on the counter for years.",
    price: 24000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "18 cm tall, 14 cm across", care: "Rinse and dry upright. No soaking." },
  },
  {
    slug: "calabash-bowl",
    number: "015",
    name: "Calabash bowl",
    room: "table",
    material: "Dried gourd",
    tagline: "Natural calabash, polished by hand",
    description:
      "A light, round bowl made from a dried calabash gourd and polished by hand. Good for fruit, bread or keys by the door. No two are the same.",
    price: 11000,
    isNew: true,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Calabash gourd", size: "About 25 cm across", care: "Wipe clean. Keep away from soaking water." },
  },
  {
    slug: "glass-tumblers-set-of-4",
    number: "019",
    name: "Glass tumblers, set of 4",
    room: "table",
    material: "Clear glass",
    tagline: "Everyday drinking glasses",
    description:
      "Four plain, sturdy tumblers for water, juice or zobo. Thick enough to survive daily use, simple enough to go with everything.",
    price: 16000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass", size: "300 ml each", care: "Dishwasher safe." },
  },
  {
    slug: "cotton-bath-towel",
    number: "005",
    name: "Cotton bath towel",
    room: "bath-linen",
    material: "Heavy cotton",
    tagline: "Thick, soft and quick to dry",
    description:
      "A generous bath towel in heavy cotton that stays soft wash after wash and dries quickly in the Lagos heat.",
    price: 18000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "100% cotton", size: "140 × 70 cm", care: "Machine wash warm. Line dry." },
  },
  {
    slug: "black-soap-bar",
    number: "003",
    name: "Black soap bar",
    room: "bath-linen",
    material: "Handmade",
    tagline: "Traditional black soap",
    description:
      "Handmade black soap from plantain ash and plant oils. Gentle on skin, rich lather, and it lasts.",
    price: 3500,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Plantain ash, palm kernel oil, shea butter", size: "150 g", care: "Keep dry between uses." },
  },
  {
    slug: "natural-hand-broom",
    number: "042",
    name: "Natural hand broom",
    room: "tools",
    material: "Natural fibre",
    tagline: "Short broom for corners and steps",
    description:
      "A short, stiff broom of natural fibres bound by hand. Gets into corners, steps and car mats that a long broom can't.",
    price: 7500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Natural fibre, cord", size: "45 cm long", care: "Shake out and hang to keep its shape." },
  },
  {
    slug: "bristle-dish-brush",
    number: "044",
    name: "Bristle dish brush",
    room: "tools",
    material: "Wood and natural bristle",
    tagline: "Wooden handle, natural bristles",
    description:
      "A wooden-handled brush with firm natural bristles for pots, pans and plates. Hang it by the sink to dry.",
    price: 4500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Beech wood, plant bristle", size: "24 cm long", care: "Rinse and hang to dry." },
  },
  {
    slug: "kraft-envelopes-pack",
    number: "055",
    name: "Kraft envelopes, pack of 20",
    room: "paper-desk",
    material: "Recycled kraft paper",
    tagline: "Plain brown envelopes",
    description:
      "Twenty plain envelopes in sturdy recycled kraft. For letters, receipts, seeds and everything else that needs keeping together.",
    price: 3000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Recycled kraft paper", size: "DL, 22 × 11 cm", care: "Keep dry." },
  },
  {
    slug: "wooden-desk-tray",
    number: "057",
    name: "Wooden desk tray",
    room: "paper-desk",
    material: "Oiled hardwood",
    tagline: "For pens, keys and small things",
    description:
      "A low tray in oiled hardwood that keeps pens, keys, glasses and small bits from wandering across the desk.",
    price: 14000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "30 × 12 cm", care: "Wipe with a dry cloth." },
  },
  {
    slug: "cast-iron-skillet",
    number: "024",
    name: "Cast iron skillet",
    room: "kitchen",
    material: "Pre-seasoned cast iron",
    tagline: "Pre-seasoned, for the stove or the coals",
    description:
      "A heavy 26 cm skillet that holds heat for frying plantain, searing fish or baking flatbread. Comes seasoned and only gets better the more you cook in it.",
    price: 38000,
    isNew: true,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Cast iron", size: "26 cm across, 2.4 kg", care: "Wash with hot water, dry on the heat, then wipe with a little oil." },
  },
  {
    slug: "glass-storage-jars-set-of-3",
    number: "033",
    name: "Glass storage jars, set of 3",
    room: "kitchen",
    material: "Clip-top glass",
    tagline: "Airtight jars for rice, beans and garri",
    description:
      "Three clip-top jars in thick glass with rubber seals, in small, medium and large. Keeps rice, beans, garri and spices dry and in sight.",
    price: 18500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass, steel clip, rubber seal", size: "0.5, 1 and 1.5 litres", care: "Dishwasher safe. Wash the seals by hand." },
  },
  {
    slug: "ceramic-serving-bowl",
    number: "011",
    name: "Ceramic serving bowl",
    room: "table",
    material: "Speckled stoneware",
    tagline: "Wide and deep, for jollof or salad",
    description:
      "A wide stoneware bowl with a speckled glaze, big enough for a pot of jollof or a salad for six. Thrown by hand, so no two are quite the same.",
    price: 16000,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [
      { name: "Speckled white", swatch: "#ece8e1" },
      { name: "Sand", swatch: "#cdb79a" },
    ],
    details: { material: "Stoneware", size: "26 cm across, 11 cm deep", care: "Dishwasher and microwave safe." },
  },
  {
    slug: "linen-napkins-set-of-4",
    number: "012",
    name: "Linen napkins, set of 4",
    room: "table",
    material: "Washed linen",
    tagline: "Soft washed linen with a hemstitch edge",
    description:
      "Four napkins in stone-washed linen with a fine hemstitched border. They soften with every wash and look better a little creased.",
    price: 14000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [
      { name: "Natural", swatch: "#c9bba5" },
      { name: "Charcoal", swatch: "#4a4744" },
      { name: "Rust", swatch: "#a65a3a" },
    ],
    details: { material: "100% linen", size: "45 × 45 cm each", care: "Machine wash at 40°C. Line dry." },
  },
  {
    slug: "woven-table-mats-set-of-4",
    number: "013",
    name: "Woven table mats, set of 4",
    room: "table",
    material: "Water hyacinth",
    tagline: "Round mats, woven by hand",
    description:
      "Four round mats woven by hand from dried water hyacinth. They protect the table from hot pots and bring a bit of texture to every meal.",
    price: 12000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Water hyacinth", size: "38 cm across each", care: "Shake out and wipe with a damp cloth. Dry flat." },
  },
];
