import type { Product } from "../lib/catalogue";

// Initial catalogue, loaded into the database by `npm run db:seed`.
export const seedProducts: Product[] = [
  {
    slug: "stoneware-mug",
    number: "014",
    name: "Stoneware mug",
    room: "table",
    material: "Ash glaze",
    tagline: "Wheel-thrown stoneware, ash glaze",
    description:
      "A heavy, round mug that holds heat. Thrown on the wheel and dipped in an ash glaze that pools a little darker at the base.",
    price: 12500,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Stoneware",
      size: "9 × 8.5 cm, 350 ml",
      care: "Dishwasher safe. Avoid sudden temperature changes.",
    },
  },
  {
    slug: "iroko-serving-board",
    number: "022",
    name: "Iroko serving board",
    room: "kitchen",
    material: "Oiled iroko wood",
    tagline: "Solid iroko, finished with food-safe oil",
    description:
      "Cut from a single piece of iroko and finished with food-safe oil. Big enough for bread, fruit or a full plate of suya.",
    price: 28000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: {
      material: "Iroko wood",
      size: "45 × 20 cm",
      care: "Hand wash and dry upright. Oil when it looks dry.",
    },
  },
  {
    slug: "enamel-pot-3-litre",
    number: "031",
    name: "Enamel pot, 3 litre",
    room: "kitchen",
    material: "Enamelled steel",
    tagline: "Enamelled steel with a fitted lid",
    description:
      "A light, bright pot for stews, rice and everything in between. Enamelled steel heats quickly and wipes clean.",
    price: 46000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Enamelled steel",
      size: "3 litres",
      care: "Wash by hand. Avoid metal scourers.",
    },
  },
  {
    slug: "linen-tea-towels-pair",
    number: "008",
    name: "Linen tea towels, pair",
    room: "bath-linen",
    material: "Washed linen",
    tagline: "Washed linen, set of two",
    description:
      "Two tea towels in pre-washed linen. They dry fast, leave no lint and get softer every wash.",
    price: 15000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: {
      material: "100% linen",
      size: "70 × 50 cm each",
      care: "Machine wash warm. Line dry.",
    },
  },
  {
    slug: "brass-wall-hooks-pair",
    number: "040",
    name: "Brass wall hooks, pair",
    room: "tools",
    material: "Solid brass",
    tagline: "Solid brass, screws included",
    description:
      "Two simple hooks in solid brass for keys, bags and towels. Left unlacquered, so they darken gently over time.",
    price: 9500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: {
      material: "Solid brass",
      size: "6 cm tall, 4 cm deep",
      care: "Wipe with a dry cloth. Polish if you prefer it bright.",
    },
  },
  {
    slug: "clay-water-pot",
    number: "017",
    name: "Clay water pot",
    room: "kitchen",
    material: "Unglazed terracotta",
    tagline: "Unglazed terracotta, with a wooden lid",
    description:
      "Unglazed clay keeps water cool the old way: a little seeps through the wall and evaporates, taking the heat with it. Thrown by hand, fired low and finished with a carved lid. Each one comes out slightly different.",
    price: 32000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [
      { name: "Natural", swatch: "#b8714f" },
      { name: "Burnished", swatch: "#8c4a2f" },
      { name: "Smoked", swatch: "#3a2f2a" },
    ],
    details: {
      material: "Terracotta, iroko lid",
      size: "5 litres · 32 × 24 cm",
      care: "Rinse with water only. No soap, no dishwasher.",
    },
  },
  {
    slug: "grid-notebook-a5",
    number: "052",
    name: "Grid notebook, A5",
    room: "paper-desk",
    material: "Recycled paper",
    tagline: "Recycled paper, lay-flat binding",
    description:
      "An A5 notebook with a faint grid, printed on recycled paper and bound to lie flat. For lists, sums and sketches.",
    price: 6500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: {
      material: "Recycled paper",
      size: "A5",
      care: "Keep dry.",
    },
  },
  {
    slug: "woven-bread-basket",
    number: "026",
    name: "Woven bread basket",
    room: "table",
    material: "Hand-woven raffia",
    tagline: "Hand-woven raffia",
    description:
      "A shallow basket woven by hand from raffia. Use it for bread, fruit or anything that needs somewhere to sit.",
    price: 18500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: {
      material: "Raffia",
      size: "30 cm across",
      care: "Shake out crumbs. Wipe with a damp cloth.",
    },
  },
  {
    slug: "wooden-spoon-set",
    number: "023",
    name: "Wooden spoon set",
    room: "kitchen",
    material: "Carved hardwood",
    tagline: "Three hand-carved cooking spoons",
    description:
      "A stirring spoon, a flat turner and a small tasting spoon, each carved from a single piece of hardwood. Smooth, sturdy and kind to every pot.",
    price: 9000,
    isNew: true,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Hardwood", size: "30, 28 and 20 cm long", care: "Hand wash and dry. Oil now and then." },
  },
  {
    slug: "wooden-mortar-and-pestle",
    number: "029",
    name: "Wooden mortar and pestle",
    room: "kitchen",
    material: "Turned hardwood",
    tagline: "For pepper, spices and garlic",
    description:
      "A deep, heavy mortar turned from hardwood, with a long pestle for pounding pepper, spices and garlic. Built to sit on the counter for years.",
    price: 24000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "18 cm tall, 14 cm across", care: "Rinse and dry upright. No soaking." },
  },
  {
    slug: "calabash-bowl",
    number: "015",
    name: "Calabash bowl",
    room: "table",
    material: "Dried gourd",
    tagline: "Natural calabash, polished by hand",
    description:
      "A light, round bowl made from a dried calabash gourd and polished by hand. Good for fruit, bread or keys by the door. No two are the same.",
    price: 11000,
    isNew: true,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Calabash gourd", size: "About 25 cm across", care: "Wipe clean. Keep away from soaking water." },
  },
  {
    slug: "glass-tumblers-set-of-4",
    number: "019",
    name: "Glass tumblers, set of 4",
    room: "table",
    material: "Clear glass",
    tagline: "Everyday drinking glasses",
    description:
      "Four plain, sturdy tumblers for water, juice or zobo. Thick enough to survive daily use, simple enough to go with everything.",
    price: 16000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass", size: "300 ml each", care: "Dishwasher safe." },
  },
  {
    slug: "cotton-bath-towel",
    number: "005",
    name: "Cotton bath towel",
    room: "bath-linen",
    material: "Heavy cotton",
    tagline: "Thick, soft and quick to dry",
    description:
      "A generous bath towel in heavy cotton that stays soft wash after wash and dries quickly in the Lagos heat.",
    price: 18000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "100% cotton", size: "140 × 70 cm", care: "Machine wash warm. Line dry." },
  },
  {
    slug: "black-soap-bar",
    number: "003",
    name: "Black soap bar",
    room: "bath-linen",
    material: "Handmade",
    tagline: "Traditional black soap",
    description:
      "Handmade black soap from plantain ash and plant oils. Gentle on skin, rich lather, and it lasts.",
    price: 3500,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Plantain ash, palm kernel oil, shea butter", size: "150 g", care: "Keep dry between uses." },
  },
  {
    slug: "natural-hand-broom",
    number: "042",
    name: "Natural hand broom",
    room: "tools",
    material: "Natural fibre",
    tagline: "Short broom for corners and steps",
    description:
      "A short, stiff broom of natural fibres bound by hand. Gets into corners, steps and car mats that a long broom can't.",
    price: 7500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Natural fibre, cord", size: "45 cm long", care: "Shake out and hang to keep its shape." },
  },
  {
    slug: "bristle-dish-brush",
    number: "044",
    name: "Bristle dish brush",
    room: "tools",
    material: "Wood and natural bristle",
    tagline: "Wooden handle, natural bristles",
    description:
      "A wooden-handled brush with firm natural bristles for pots, pans and plates. Hang it by the sink to dry.",
    price: 4500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Beech wood, plant bristle", size: "24 cm long", care: "Rinse and hang to dry." },
  },
  {
    slug: "kraft-envelopes-pack",
    number: "055",
    name: "Kraft envelopes, pack of 20",
    room: "paper-desk",
    material: "Recycled kraft paper",
    tagline: "Plain brown envelopes",
    description:
      "Twenty plain envelopes in sturdy recycled kraft. For letters, receipts, seeds and everything else that needs keeping together.",
    price: 3000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Recycled kraft paper", size: "DL, 22 × 11 cm", care: "Keep dry." },
  },
  {
    slug: "wooden-desk-tray",
    number: "057",
    name: "Wooden desk tray",
    room: "paper-desk",
    material: "Oiled hardwood",
    tagline: "For pens, keys and small things",
    description:
      "A low tray in oiled hardwood that keeps pens, keys, glasses and small bits from wandering across the desk.",
    price: 14000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "30 × 12 cm", care: "Wipe with a dry cloth." },
  },
  {
    slug: "cast-iron-skillet",
    number: "024",
    name: "Cast iron skillet",
    room: "kitchen",
    material: "Pre-seasoned cast iron",
    tagline: "Pre-seasoned, for the stove or the coals",
    description:
      "A heavy 26 cm skillet that holds heat for frying plantain, searing fish or baking flatbread. Comes seasoned and only gets better the more you cook in it.",
    price: 38000,
    isNew: true,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Cast iron", size: "26 cm across, 2.4 kg", care: "Wash with hot water, dry on the heat, then wipe with a little oil." },
  },
  {
    slug: "glass-storage-jars-set-of-3",
    number: "033",
    name: "Glass storage jars, set of 3",
    room: "kitchen",
    material: "Clip-top glass",
    tagline: "Airtight jars for rice, beans and garri",
    description:
      "Three clip-top jars in thick glass with rubber seals, in small, medium and large. Keeps rice, beans, garri and spices dry and in sight.",
    price: 18500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass, steel clip, rubber seal", size: "0.5, 1 and 1.5 litres", care: "Dishwasher safe. Wash the seals by hand." },
  },
  {
    slug: "ceramic-serving-bowl",
    number: "011",
    name: "Ceramic serving bowl",
    room: "table",
    material: "Speckled stoneware",
    tagline: "Wide and deep, for jollof or salad",
    description:
      "A wide stoneware bowl with a speckled glaze, big enough for a pot of jollof or a salad for six. Thrown by hand, so no two are quite the same.",
    price: 16000,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [
      { name: "Speckled white", swatch: "#ece8e1" },
      { name: "Sand", swatch: "#cdb79a" },
    ],
    details: { material: "Stoneware", size: "26 cm across, 11 cm deep", care: "Dishwasher and microwave safe." },
  },
  {
    slug: "linen-napkins-set-of-4",
    number: "012",
    name: "Linen napkins, set of 4",
    room: "table",
    material: "Washed linen",
    tagline: "Soft washed linen with a hemstitch edge",
    description:
      "Four napkins in stone-washed linen with a fine hemstitched border. They soften with every wash and look better a little creased.",
    price: 14000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [
      { name: "Natural", swatch: "#c9bba5" },
      { name: "Charcoal", swatch: "#4a4744" },
      { name: "Rust", swatch: "#a65a3a" },
    ],
    details: { material: "100% linen", size: "45 × 45 cm each", care: "Machine wash at 40°C. Line dry." },
  },
  {
    slug: "woven-table-mats-set-of-4",
    number: "013",
    name: "Woven table mats, set of 4",
    room: "table",
    material: "Water hyacinth",
    tagline: "Round mats, woven by hand",
    description:
      "Four round mats woven by hand from dried water hyacinth. They protect the table from hot pots and bring a bit of texture to every meal.",
    price: 12000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Water hyacinth", size: "38 cm across each", care: "Shake out and wipe with a damp cloth. Dry flat." },
  },
  {
    slug: "waffle-hand-towel",
    number: "006",
    name: "Waffle hand towel",
    room: "bath-linen",
    material: "Cotton waffle weave",
    tagline: "Light, quick-drying cotton waffle",
    description:
      "A hand towel in deep cotton waffle weave. Light and quick to dry in humid weather, and it gets softer with every wash.",
    price: 7500,
    isNew: true,
    tone: "#e3ded6",
    finishes: [
      { name: "Cream", swatch: "#ece4d3" },
      { name: "Mustard", swatch: "#d29b2b" },
    ],
    details: { material: "100% cotton", size: "50 × 90 cm", care: "Machine wash at 60°C. Tumble dry low." },
  },
  {
    slug: "woven-laundry-basket",
    number: "007",
    name: "Woven laundry basket",
    room: "bath-linen",
    material: "Seagrass",
    tagline: "Tall basket with rope handles",
    description:
      "A tall, sturdy basket woven from seagrass with two rope handles. Holds a week of laundry, towels or toys and looks good doing it.",
    price: 26000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Seagrass", size: "45 cm tall, 40 cm across", care: "Keep dry. Brush off dust." },
  },
  {
    slug: "natural-loofah-sponge",
    number: "004",
    name: "Natural loofah sponge",
    room: "bath-linen",
    material: "Dried loofah gourd",
    tagline: "Grown, dried and cut, nothing added",
    description:
      "A plant-based scrub cut from a dried loofah gourd. Firm when dry, softer when wet, and fully compostable when it is done.",
    price: 2500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Loofah gourd", size: "About 12 cm long", care: "Rinse and hang to dry after use. Replace every few months." },
  },
  {
    slug: "galvanised-watering-can",
    number: "046",
    name: "Galvanised watering can",
    room: "tools",
    material: "Galvanised steel",
    tagline: "Five litres, with a brass rose",
    description:
      "A classic watering can in galvanised steel with a removable rose for a gentle shower. For balcony pots, herbs and the garden.",
    price: 22000,
    isNew: true,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Galvanised steel, brass rose", size: "5 litres", care: "Empty after use and store upside down." },
  },
  {
    slug: "wooden-clothes-pegs",
    number: "048",
    name: "Wooden clothes pegs, 24",
    room: "tools",
    material: "Beech wood",
    tagline: "Strong spring pegs in plain beech",
    description:
      "Twenty-four pegs in smooth beech with steel springs. They grip heavy towels and jeans without leaving marks, and last for years in the sun.",
    price: 3000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Beech wood, steel spring", size: "7 cm long", care: "Bring in when not in use." },
  },
  {
    slug: "graphite-pencils-set-of-6",
    number: "050",
    name: "Graphite pencils, set of 6",
    room: "paper-desk",
    material: "Cedar and graphite",
    tagline: "From hard to soft, 2H to 6B",
    description:
      "Six drawing pencils in cedar, from 2H for fine lines to 6B for deep shading. Sharpen easily and feel good in the hand.",
    price: 4000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Cedar wood, graphite", size: "17.5 cm", care: "Sharpen with a blade or sharpener." },
  },
  {
    slug: "spiral-sketchbook-a4",
    number: "053",
    name: "Spiral sketchbook, A4",
    room: "paper-desk",
    material: "Heavy cream paper",
    tagline: "80 sheets of heavy, smooth paper",
    description:
      "A spiral-bound A4 sketchbook with 80 sheets of heavy cream paper that takes pencil, ink and light washes. Lies flat on any page.",
    price: 9500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "160 gsm paper, kraft cover", size: "A4, 80 sheets", care: "Keep dry." },
  },
  {
    slug: "enamel-kettle",
    number: "060",
    name: "Enamel kettle",
    room: "kitchen",
    material: "Enamelled steel",
    tagline: "Whistles when the water's ready",
    description:
      "A two-litre kettle in enamelled steel that works on gas, electric and the coal pot. The whistle tells you when the water is boiling.",
    price: 21000,
    isNew: true,
    tone: "#dbd6cd",
    finishes: [
      { name: "Green", swatch: "#7fae3c" },
      { name: "Red", swatch: "#c8371f" },
    ],
    details: { material: "Enamelled steel", size: "2 litres", care: "Wipe clean. Don't let it boil dry." },
  },
  {
    slug: "chef-knife-20cm",
    number: "061",
    name: "Chef's knife, 20 cm",
    room: "kitchen",
    material: "Carbon steel, wooden handle",
    tagline: "One sharp knife for nearly everything",
    description:
      "A 20 cm carbon steel blade on a riveted wooden handle. Chops onions, peppers and yam with ease and takes a keen edge on a stone.",
    price: 27000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Carbon steel, hardwood", size: "20 cm blade", care: "Hand wash and dry straight away. Oil the blade now and then." },
  },
  {
    slug: "wooden-rolling-pin",
    number: "062",
    name: "Wooden rolling pin",
    room: "kitchen",
    material: "Turned hardwood",
    tagline: "For chin chin, puff-puff and pastry",
    description:
      "A plain, heavy rolling pin turned from one piece of hardwood. Rolls chin chin dough, pastry and flatbread evenly.",
    price: 6500,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "45 cm long", care: "Wipe clean. Don't soak." },
  },
  {
    slug: "ceramic-teapot",
    number: "063",
    name: "Ceramic teapot",
    room: "kitchen",
    material: "Glazed stoneware",
    tagline: "Holds four cups, pours without dripping",
    description:
      "A round stoneware teapot with a lid that stays put and a spout that doesn't drip. Holds enough for four cups of tea or zobo.",
    price: 19500,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [
      { name: "White", swatch: "#efece6" },
      { name: "Navy", swatch: "#243350" },
    ],
    details: { material: "Stoneware", size: "1 litre", care: "Dishwasher safe." },
  },
  {
    slug: "glass-water-jug",
    number: "064",
    name: "Glass water jug",
    room: "kitchen",
    material: "Clear glass",
    tagline: "For cold water, juice and zobo",
    description:
      "A tall jug in clear, heavy glass. Fits in the fridge door and pours cleanly.",
    price: 9000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass", size: "1.5 litres", care: "Dishwasher safe." },
  },
  {
    slug: "steel-colander",
    number: "065",
    name: "Steel colander",
    room: "kitchen",
    material: "Stainless steel",
    tagline: "Drains rice, pasta and washed greens",
    description:
      "A deep colander in stainless steel with two handles and a stable base. Drains rice, beans and washed ugwu quickly.",
    price: 11500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Stainless steel", size: "26 cm across", care: "Dishwasher safe." },
  },
  {
    slug: "box-grater",
    number: "066",
    name: "Box grater",
    room: "kitchen",
    material: "Stainless steel",
    tagline: "Four sides, from coarse to fine",
    description:
      "A sturdy four-sided grater for cheese, carrots, ginger and nutmeg. Stands firmly on the board.",
    price: 7000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Stainless steel", size: "24 cm tall", care: "Dishwasher safe. Brush clean." },
  },
  {
    slug: "cast-iron-dutch-oven",
    number: "067",
    name: "Cast iron Dutch oven",
    room: "kitchen",
    material: "Enamelled cast iron",
    tagline: "For stews, soups and slow-cooked beans",
    description:
      "A heavy enamelled pot that holds heat for hours. Made for stew, pepper soup and beans that cook low and slow.",
    price: 85000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [
      { name: "Red", swatch: "#a63a2b" },
      { name: "Black", swatch: "#262422" },
    ],
    details: { material: "Enamelled cast iron", size: "4.5 litres, 24 cm", care: "Hand wash. Use wooden or silicone spoons." },
  },
  {
    slug: "wooden-chopping-board",
    number: "068",
    name: "Wooden chopping board",
    room: "kitchen",
    material: "Oiled hardwood",
    tagline: "Thick end-grain board, kind to knives",
    description:
      "A thick hardwood board that stays put on the counter and is kind to knife edges. Oiled and ready to use.",
    price: 19000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Hardwood", size: "40 × 28 × 3 cm", care: "Hand wash and dry upright. Oil monthly." },
  },
  {
    slug: "ceramic-oil-bottle",
    number: "069",
    name: "Ceramic oil bottle",
    room: "kitchen",
    material: "Glazed stoneware",
    tagline: "For palm oil or groundnut oil by the stove",
    description:
      "A stoneware bottle with a cork stopper for keeping oil by the stove. Pours in a thin line without mess.",
    price: 8500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Stoneware, cork", size: "500 ml", care: "Hand wash." },
  },
  {
    slug: "spice-tins-set-of-6",
    number: "070",
    name: "Spice tins, set of 6",
    room: "kitchen",
    material: "Tin-plated steel",
    tagline: "Airtight tins for pepper, curry and thyme",
    description:
      "Six small airtight tins with clear lids, so you can see the crayfish, curry and thyme at a glance.",
    price: 12000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Tin-plated steel, glass", size: "100 ml each", care: "Wipe clean. Keep dry." },
  },
  {
    slug: "measuring-cups",
    number: "071",
    name: "Measuring cups, set of 4",
    room: "kitchen",
    material: "Copper-plated steel",
    tagline: "From a quarter cup to one cup",
    description:
      "Four nesting measuring cups that hang on a ring. For baking chin chin, cake and bread.",
    price: 9500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Copper-plated stainless steel", size: "¼, ⅓, ½ and 1 cup", care: "Hand wash." },
  },
  {
    slug: "clay-cooking-pot",
    number: "072",
    name: "Clay cooking pot",
    room: "kitchen",
    material: "Fired clay",
    tagline: "For egusi and soups that taste of the pot",
    description:
      "A round pot in fired clay for cooking soups and stews slowly. The clay gives a gentle, even heat.",
    price: 23000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Fired clay", size: "3 litres", care: "Season before first use. Wash with water only." },
  },
  {
    slug: "wooden-spatula-set",
    number: "073",
    name: "Wooden spatula set",
    room: "kitchen",
    material: "Olive wood",
    tagline: "Three spatulas for stirring and turning",
    description:
      "Three spatulas carved from olive wood: a flat turner, a slotted one and a corner spoon. Won't scratch pans.",
    price: 8000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Olive wood", size: "30 cm", care: "Hand wash. Oil when dry." },
  },
  {
    slug: "enamel-mugs-set-of-2",
    number: "074",
    name: "Enamel mugs, set of 2",
    room: "table",
    material: "Enamelled steel",
    tagline: "For tea at home or on the road",
    description:
      "Two classic enamel mugs with a dark rim. Light, tough and hard to break.",
    price: 7500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [
      { name: "White", swatch: "#efece6" },
      { name: "Black", swatch: "#262422" },
    ],
    details: { material: "Enamelled steel", size: "350 ml each", care: "Dishwasher safe." },
  },
  {
    slug: "dinner-plates-set-of-4",
    number: "075",
    name: "Dinner plates, set of 4",
    room: "table",
    material: "Glazed stoneware",
    tagline: "Wide rims, made for rice and stew",
    description:
      "Four stoneware dinner plates with a soft glaze and a wide rim, roomy enough for rice, stew and plantain.",
    price: 32000,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [
      { name: "Speckled white", swatch: "#ece8e1" },
      { name: "Sand", swatch: "#cdb79a" },
    ],
    details: { material: "Stoneware", size: "27 cm across", care: "Dishwasher and microwave safe." },
  },
  {
    slug: "wooden-salad-servers",
    number: "076",
    name: "Wooden salad servers",
    room: "table",
    material: "Carved hardwood",
    tagline: "A pair for salads and rice",
    description:
      "A pair of long servers carved from hardwood. For tossing salad and serving rice at the table.",
    price: 6500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Hardwood", size: "30 cm", care: "Hand wash. Oil when dry." },
  },
  {
    slug: "brass-candle-holder",
    number: "077",
    name: "Brass candle holder",
    room: "table",
    material: "Solid brass",
    tagline: "For dinner, and for when the light goes",
    description:
      "A heavy brass candle holder that will outlast many power cuts. Takes standard dinner candles.",
    price: 11000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Solid brass", size: "10 cm tall", care: "Polish with a soft cloth." },
  },
  {
    slug: "linen-tablecloth",
    number: "078",
    name: "Linen tablecloth",
    room: "table",
    material: "Washed linen",
    tagline: "Soft washed linen for a six-seater",
    description:
      "A tablecloth in stone-washed linen, soft from the first use. Sized for a table for six.",
    price: 38000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [
      { name: "Natural", swatch: "#c9bba5" },
      { name: "White", swatch: "#efece6" },
    ],
    details: { material: "100% linen", size: "150 × 250 cm", care: "Machine wash at 40°C. Line dry." },
  },
  {
    slug: "stoneware-cups-set-of-4",
    number: "079",
    name: "Stoneware cups, set of 4",
    room: "table",
    material: "Glazed stoneware",
    tagline: "Small cups for coffee or tea",
    description:
      "Four small handleless cups thrown in stoneware. For coffee, tea or a little kunu.",
    price: 14000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Stoneware", size: "150 ml each", care: "Dishwasher safe." },
  },
  {
    slug: "woven-fruit-basket",
    number: "080",
    name: "Woven fruit basket",
    room: "table",
    material: "Hand-woven raffia",
    tagline: "For oranges, mangoes and bread",
    description:
      "A shallow round basket woven from raffia. Keeps fruit in sight and lets it breathe.",
    price: 9500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Raffia", size: "32 cm across", care: "Shake out and keep dry." },
  },
  {
    slug: "ceramic-bud-vase",
    number: "081",
    name: "Ceramic bud vase",
    room: "table",
    material: "Glazed stoneware",
    tagline: "For one stem or a sprig of leaves",
    description:
      "A small stoneware vase for a single flower or a cutting from the garden.",
    price: 6000,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Stoneware", size: "14 cm tall", care: "Hand wash." },
  },
  {
    slug: "wooden-serving-tray",
    number: "082",
    name: "Wooden serving tray",
    room: "table",
    material: "Oiled teak",
    tagline: "Carry breakfast, tea or drinks",
    description:
      "A wide teak tray with cut-out handles for carrying breakfast to bed or drinks to the balcony.",
    price: 21000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Teak", size: "50 × 35 cm", care: "Wipe clean. Oil when dry." },
  },
  {
    slug: "wooden-bowls-set-of-2",
    number: "083",
    name: "Wooden bowls, set of 2",
    room: "table",
    material: "Turned hardwood",
    tagline: "For snacks, groundnuts and salad",
    description:
      "Two turned hardwood bowls in different sizes, for groundnuts, chin chin or a small salad.",
    price: 13000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Hardwood", size: "15 and 20 cm across", care: "Hand wash. Oil when dry." },
  },
  {
    slug: "wooden-pepper-mill",
    number: "084",
    name: "Wooden pepper mill",
    room: "table",
    material: "Beech, ceramic grinder",
    tagline: "Fresh pepper, coarse or fine",
    description:
      "A tall beech mill with a ceramic grinder you can set from coarse to fine.",
    price: 12500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Beech, ceramic", size: "20 cm tall", care: "Wipe clean. Don't wash the grinder." },
  },
  {
    slug: "brass-cutlery-set",
    number: "085",
    name: "Brass cutlery, 4 settings",
    room: "table",
    material: "Brass-finish steel",
    tagline: "Knives, forks and spoons for four",
    description:
      "Sixteen pieces in steel with a warm brass finish: knife, fork, spoon and teaspoon for four people.",
    price: 42000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Stainless steel, brass finish", size: "16 pieces", care: "Hand wash to keep the finish." },
  },
  {
    slug: "coasters-set-of-6",
    number: "086",
    name: "Coasters, set of 6",
    room: "table",
    material: "Cork and wood",
    tagline: "Keep rings off the table",
    description:
      "Six round coasters that protect the table from cold glasses and hot cups.",
    price: 4500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Cork, wood", size: "10 cm across", care: "Wipe clean." },
  },
  {
    slug: "glass-carafe",
    number: "087",
    name: "Glass carafe",
    room: "table",
    material: "Mouth-blown glass",
    tagline: "Water for the table, with a cup lid",
    description:
      "A mouth-blown carafe with a glass that sits upside down on top as a lid. For the table or the bedside.",
    price: 11000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass", size: "1 litre", care: "Hand wash." },
  },
  {
    slug: "cotton-bathrobe",
    number: "088",
    name: "Cotton bathrobe",
    room: "bath-linen",
    material: "Cotton waffle",
    tagline: "Light enough for Lagos heat",
    description:
      "A light waffle-weave robe in cotton that dries fast and doesn't feel heavy in the heat.",
    price: 29000,
    isNew: true,
    tone: "#e3ded6",
    finishes: [
      { name: "White", swatch: "#efece6" },
      { name: "Grey", swatch: "#9a958d" },
    ],
    details: { material: "100% cotton", size: "One size", care: "Machine wash at 40°C." },
  },
  {
    slug: "cotton-bath-mat",
    number: "089",
    name: "Cotton bath mat",
    room: "bath-linen",
    material: "Thick cotton",
    tagline: "Soft underfoot, dries quickly",
    description:
      "A thick cotton bath mat that soaks up water and dries quickly between showers.",
    price: 9500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "100% cotton", size: "50 × 80 cm", care: "Machine wash at 40°C." },
  },
  {
    slug: "wooden-bath-brush",
    number: "090",
    name: "Wooden bath brush",
    room: "bath-linen",
    material: "Beech and natural bristle",
    tagline: "Long handle for your back",
    description:
      "A long-handled beech brush with natural bristles for scrubbing your back and dry brushing.",
    price: 7500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Beech, natural bristle", size: "40 cm", care: "Hang to dry after use." },
  },
  {
    slug: "linen-pillowcases-pair",
    number: "091",
    name: "Linen pillowcases, pair",
    room: "bath-linen",
    material: "Washed linen",
    tagline: "Cool to sleep on in the heat",
    description:
      "Two pillowcases in stone-washed linen that stay cool and soften with every wash.",
    price: 16000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [
      { name: "White", swatch: "#efece6" },
      { name: "Natural", swatch: "#c9bba5" },
      { name: "Clay", swatch: "#b07a5e" },
    ],
    details: { material: "100% linen", size: "50 × 75 cm", care: "Machine wash at 40°C." },
  },
  {
    slug: "cotton-bed-sheet",
    number: "092",
    name: "Cotton bed sheet",
    room: "bath-linen",
    material: "Percale cotton",
    tagline: "Crisp, cool percale",
    description:
      "A flat sheet in cotton percale: crisp, breathable and cool for hot nights.",
    price: 24000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "100% cotton percale", size: "Double, 230 × 260 cm", care: "Machine wash at 60°C." },
  },
  {
    slug: "woven-throw",
    number: "093",
    name: "Woven cotton throw",
    room: "bath-linen",
    material: "Hand-woven cotton",
    tagline: "For the sofa, or harmattan nights",
    description:
      "A hand-woven cotton throw with fringed ends. Light enough for the sofa, warm enough for harmattan mornings.",
    price: 33000,
    isNew: true,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "100% cotton", size: "130 × 180 cm", care: "Hand wash cold. Dry flat." },
  },
  {
    slug: "raw-shea-butter",
    number: "094",
    name: "Raw shea butter",
    room: "bath-linen",
    material: "Unrefined shea",
    tagline: "Pure shea from northern Nigeria",
    description:
      "Unrefined shea butter made by women's cooperatives in northern Nigeria. For skin, hair and lips.",
    price: 5000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Unrefined shea butter", size: "250 g", care: "Keep cool and out of the sun." },
  },
  {
    slug: "wooden-comb",
    number: "095",
    name: "Wooden comb",
    room: "bath-linen",
    material: "Sandalwood",
    tagline: "Wide teeth, gentle on hair",
    description:
      "A wide-tooth comb cut from sandalwood. Glides through thick hair without snagging.",
    price: 3500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Sandalwood", size: "15 cm", care: "Wipe clean." },
  },
  {
    slug: "ceramic-soap-dish",
    number: "096",
    name: "Ceramic soap dish",
    room: "bath-linen",
    material: "Glazed stoneware",
    tagline: "Raised ridges keep soap dry",
    description:
      "A stoneware dish with ridges that let water drain so your black soap lasts longer.",
    price: 4500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Stoneware", size: "12 × 9 cm", care: "Rinse clean." },
  },
  {
    slug: "bamboo-toothbrushes-4",
    number: "097",
    name: "Bamboo toothbrushes, 4",
    room: "bath-linen",
    material: "Bamboo, soft bristle",
    tagline: "A plastic-free swap",
    description:
      "Four toothbrushes with bamboo handles and soft bristles. The handles can be composted.",
    price: 3000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Bamboo, nylon bristle", size: "19 cm", care: "Rinse and stand to dry." },
  },
  {
    slug: "cotton-face-cloths-3",
    number: "098",
    name: "Cotton face cloths, 3",
    room: "bath-linen",
    material: "Cotton terry",
    tagline: "Soft terry, washes well",
    description:
      "Three small face cloths in soft cotton terry for washing and wiping.",
    price: 4500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "100% cotton", size: "30 × 30 cm", care: "Machine wash at 60°C." },
  },
  {
    slug: "linen-shower-curtain",
    number: "099",
    name: "Linen shower curtain",
    room: "bath-linen",
    material: "Linen-cotton",
    tagline: "Soft fabric instead of plastic",
    description:
      "A shower curtain in a linen-cotton blend that hangs softly and dries quickly. Use with a liner.",
    price: 21000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Linen, cotton", size: "180 × 200 cm", care: "Machine wash at 40°C." },
  },
  {
    slug: "glass-soap-dispenser",
    number: "100",
    name: "Glass soap dispenser",
    room: "bath-linen",
    material: "Glass, steel pump",
    tagline: "For liquid soap by the sink",
    description:
      "A heavy glass bottle with a steel pump. Fill it with liquid black soap or hand wash.",
    price: 6500,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Glass, stainless steel", size: "300 ml", care: "Rinse before refilling." },
  },
  {
    slug: "rattan-mirror",
    number: "101",
    name: "Rattan mirror",
    room: "bath-linen",
    material: "Hand-woven rattan",
    tagline: "Round mirror in a woven frame",
    description:
      "A round mirror framed in hand-woven rattan for the bathroom or hallway.",
    price: 36000,
    isNew: true,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Rattan, glass", size: "50 cm across", care: "Dust with a dry brush." },
  },
  {
    slug: "claw-hammer",
    number: "102",
    name: "Claw hammer",
    room: "tools",
    material: "Steel, hardwood handle",
    tagline: "For nails, frames and small repairs",
    description:
      "A balanced claw hammer with a steel head and hardwood handle for hanging frames and fixing furniture.",
    price: 9500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Forged steel, hickory", size: "450 g head", care: "Keep dry." },
  },
  {
    slug: "screwdriver-set",
    number: "103",
    name: "Screwdriver set, 6",
    room: "tools",
    material: "Steel, wooden handles",
    tagline: "Flat and cross heads in common sizes",
    description:
      "Six screwdrivers in the sizes you actually need, with comfortable wooden handles.",
    price: 12000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Chrome vanadium steel, wood", size: "6 pieces", care: "Keep dry." },
  },
  {
    slug: "tape-measure",
    number: "104",
    name: "Tape measure, 5 m",
    room: "tools",
    material: "Steel tape",
    tagline: "Metric and inches, locks in place",
    description:
      "A 5 m steel tape with a lock and a belt clip. For curtains, furniture and the tailor.",
    price: 5500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Steel, ABS case", size: "5 m", care: "Wipe the tape clean." },
  },
  {
    slug: "garden-trowel",
    number: "105",
    name: "Garden trowel",
    room: "tools",
    material: "Steel, ash handle",
    tagline: "For pots, herbs and planting out",
    description:
      "A strong trowel with a pointed steel blade for potting plants and planting out herbs.",
    price: 7000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Stainless steel, ash", size: "30 cm", care: "Wipe clean after use." },
  },
  {
    slug: "pruning-shears",
    number: "106",
    name: "Pruning shears",
    room: "tools",
    material: "Carbon steel",
    tagline: "Clean cuts on stems and branches",
    description:
      "Bypass shears that make clean cuts on stems and small branches. A spring and a lock keep them safe.",
    price: 11500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Carbon steel", size: "20 cm", care: "Wipe and oil the blades." },
  },
  {
    slug: "leather-work-gloves",
    number: "107",
    name: "Leather work gloves",
    room: "tools",
    material: "Cowhide leather",
    tagline: "For the garden and rough jobs",
    description:
      "Tough cowhide gloves for gardening, moving things and rough jobs.",
    price: 8000,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Cowhide", size: "One size", care: "Brush off dirt. Air dry." },
  },
  {
    slug: "wooden-step-stool",
    number: "108",
    name: "Wooden step stool",
    room: "tools",
    material: "Solid hardwood",
    tagline: "Two steps up to the top shelf",
    description:
      "A sturdy two-step stool in hardwood. Reaches the top shelf and doubles as a seat.",
    price: 32000,
    isNew: true,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Hardwood", size: "50 cm tall", care: "Wipe clean." },
  },
  {
    slug: "dustpan-and-brush",
    number: "109",
    name: "Dustpan and brush",
    room: "tools",
    material: "Steel and wood",
    tagline: "Sweeps up sand and crumbs",
    description:
      "A metal dustpan with a wooden-handled brush that clips on for storage.",
    price: 8500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Steel, beech, natural bristle", size: "30 cm", care: "Shake out after use." },
  },
  {
    slug: "galvanised-bucket",
    number: "110",
    name: "Galvanised bucket",
    room: "tools",
    material: "Galvanised steel",
    tagline: "Ten litres, rust resistant",
    description:
      "A ten-litre bucket in galvanised steel with a sturdy wire handle. For washing, mopping and the garden.",
    price: 9500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Galvanised steel", size: "10 litres", care: "Rinse and dry." },
  },
  {
    slug: "steel-scissors",
    number: "111",
    name: "Steel scissors",
    room: "tools",
    material: "Forged steel",
    tagline: "Sharp, heavy, made to last",
    description:
      "Forged steel scissors that cut cloth, paper and string cleanly and can be sharpened for years.",
    price: 8500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Forged steel", size: "21 cm", care: "Oil the pivot now and then." },
  },
  {
    slug: "jute-twine",
    number: "112",
    name: "Jute twine",
    room: "tools",
    material: "Natural jute",
    tagline: "For parcels, plants and the kitchen",
    description:
      "A large ball of natural jute twine for tying parcels, staking plants and trussing.",
    price: 2500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Jute", size: "100 m", care: "Keep dry." },
  },
  {
    slug: "hurricane-lantern",
    number: "113",
    name: "Hurricane lantern",
    room: "tools",
    material: "Steel and glass",
    tagline: "Steady light when the power goes",
    description:
      "A classic paraffin lantern with a glass chimney and an adjustable wick. Steady light when NEPA takes it.",
    price: 14000,
    isNew: true,
    tone: "#dbd6cd",
    finishes: [
      { name: "Silver", swatch: "#b9b7b2" },
      { name: "Black", swatch: "#262422" },
    ],
    details: { material: "Steel, glass", size: "25 cm tall", care: "Trim the wick. Use outdoors or with ventilation." },
  },
  {
    slug: "hand-saw",
    number: "114",
    name: "Hand saw",
    room: "tools",
    material: "Steel, wooden handle",
    tagline: "For timber and small building jobs",
    description:
      "A 50 cm hand saw with hardened teeth and a wooden handle, for cutting timber and boards.",
    price: 13500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Hardened steel, wood", size: "50 cm", care: "Wipe and oil the blade." },
  },
  {
    slug: "spirit-level",
    number: "115",
    name: "Spirit level",
    room: "tools",
    material: "Aluminium",
    tagline: "Hang frames and shelves straight",
    description:
      "A 60 cm aluminium level with three vials for hanging shelves and frames straight.",
    price: 9000,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Aluminium", size: "60 cm", care: "Wipe clean." },
  },
  {
    slug: "brass-padlock",
    number: "116",
    name: "Brass padlock",
    room: "tools",
    material: "Solid brass",
    tagline: "With three keys",
    description:
      "A solid brass padlock with a hardened shackle and three keys. Won't rust in the rain.",
    price: 6500,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass, hardened steel", size: "40 mm", care: "Oil the keyhole once a year." },
  },
  {
    slug: "fountain-pen",
    number: "117",
    name: "Fountain pen",
    room: "paper-desk",
    material: "Steel nib",
    tagline: "Smooth writing, refillable",
    description:
      "A fountain pen with a medium steel nib and a converter so you can fill it from a bottle.",
    price: 18000,
    isNew: true,
    tone: "#e7e3dc",
    finishes: [
      { name: "Black", swatch: "#262422" },
      { name: "Green", swatch: "#3e5a4a" },
    ],
    details: { material: "Resin, steel", size: "14 cm", care: "Flush with water when changing ink." },
  },
  {
    slug: "ink-bottle",
    number: "118",
    name: "Bottled ink",
    room: "paper-desk",
    material: "Fountain pen ink",
    tagline: "Deep blue-black, 50 ml",
    description:
      "A 50 ml bottle of blue-black fountain pen ink that dries quickly and doesn't feather.",
    price: 6000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Water-based ink", size: "50 ml", care: "Keep the cap closed." },
  },
  {
    slug: "leather-journal",
    number: "119",
    name: "Leather journal",
    room: "paper-desk",
    material: "Vegetable-tanned leather",
    tagline: "Refillable cover, plain pages",
    description:
      "A soft leather cover with a plain paper notebook inside. When it's full, slip in a new one.",
    price: 22000,
    isNew: true,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Leather, 100 gsm paper", size: "A5, 192 pages", care: "Rub with leather balm when dry." },
  },
  {
    slug: "brass-desk-lamp",
    number: "120",
    name: "Brass desk lamp",
    room: "paper-desk",
    material: "Brass and steel",
    tagline: "Adjustable arm, warm light",
    description:
      "A desk lamp with an adjustable arm and a brass shade. Takes a standard E27 bulb.",
    price: 48000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass, steel", size: "45 cm tall", care: "Dust with a dry cloth." },
  },
  {
    slug: "brass-letter-opener",
    number: "121",
    name: "Brass letter opener",
    room: "paper-desk",
    material: "Solid brass",
    tagline: "For letters and parcels",
    description:
      "A solid brass letter opener that slits envelopes cleanly and sits nicely on the desk.",
    price: 5500,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass", size: "20 cm", care: "Polish with a soft cloth." },
  },
  {
    slug: "metal-stapler",
    number: "122",
    name: "Metal stapler",
    room: "paper-desk",
    material: "Steel",
    tagline: "Staples up to 25 sheets",
    description:
      "A heavy steel stapler that staples up to 25 sheets and doesn't jam.",
    price: 8500,
    isNew: false,
    tone: "#dbd6cd",
    finishes: [],
    details: { material: "Steel", size: "16 cm", care: "Use 24/6 staples." },
  },
  {
    slug: "brass-paper-clips",
    number: "123",
    name: "Brass paper clips, 100",
    room: "paper-desk",
    material: "Brass",
    tagline: "A tin of a hundred",
    description:
      "A hundred brass-coloured paper clips in a small tin.",
    price: 2000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass-plated steel", size: "28 mm", care: "Keep dry." },
  },
  {
    slug: "wooden-ruler",
    number: "124",
    name: "Wooden ruler, 30 cm",
    room: "paper-desk",
    material: "Beech",
    tagline: "Clear markings, steel edge",
    description:
      "A 30 cm beech ruler with clear printed markings and a steel edge for cutting.",
    price: 2500,
    isNew: false,
    tone: "#d8cfc0",
    finishes: [],
    details: { material: "Beech, steel", size: "30 cm", care: "Wipe clean." },
  },
  {
    slug: "brass-pencil-sharpener",
    number: "125",
    name: "Brass pencil sharpener",
    room: "paper-desk",
    material: "Solid brass",
    tagline: "Small, heavy and sharp",
    description:
      "A solid brass sharpener with a replaceable blade. Gives pencils a long, clean point.",
    price: 3000,
    isNew: false,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass, steel blade", size: "2.5 cm", care: "Empty shavings after use." },
  },
  {
    slug: "ceramic-pen-pot",
    number: "126",
    name: "Ceramic pen pot",
    room: "paper-desk",
    material: "Glazed stoneware",
    tagline: "For pens, pencils and scissors",
    description:
      "A simple stoneware pot that keeps pens, pencils and scissors in one place.",
    price: 6000,
    isNew: false,
    tone: "#e7e3dc",
    finishes: [],
    details: { material: "Stoneware", size: "10 cm tall", care: "Wipe clean." },
  },
  {
    slug: "wax-seal-kit",
    number: "128",
    name: "Wax seal kit",
    room: "paper-desk",
    material: "Brass and wax",
    tagline: "Seal letters the old way",
    description:
      "A brass seal stamp with a wooden handle and three sticks of sealing wax for letters and invitations.",
    price: 11000,
    isNew: true,
    tone: "#d3c9b8",
    finishes: [],
    details: { material: "Brass, wood, wax", size: "Stamp 25 mm", care: "Let wax cool before lifting the stamp." },
  },
  {
    slug: "postcards-set-of-10",
    number: "129",
    name: "Postcards, set of 10",
    room: "paper-desk",
    material: "Recycled card",
    tagline: "Ten blank cards for short notes",
    description:
      "Ten blank postcards in thick recycled card, for thank-yous and short notes.",
    price: 3500,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Recycled card", size: "A6", care: "Keep dry." },
  },
  {
    slug: "desk-calendar",
    number: "130",
    name: "Desk calendar",
    room: "paper-desk",
    material: "Recycled paper",
    tagline: "One page a month",
    description:
      "A month-to-a-page desk calendar on a stand, printed on recycled paper.",
    price: 5000,
    isNew: false,
    tone: "#e3ded6",
    finishes: [],
    details: { material: "Recycled paper, card stand", size: "A5", care: "Keep dry." },
  },
];
